name: npm - Cache with Skip

on:  
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: NodeWebApp

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: NodeWebApp/package-lock.json
    - run: npm install
